### PR TITLE
2nd try to fix

### LINKED ISSUE #68: peripheral.discoverServices with empty list []
When using the mock the call to `.discoverServices` returns with am empty list.

Expected: the call should return all `mockServices` when supplying an empty list `([])`.

Documentation to this call from Apple states:
> Discussion
> 
> You can provide an array of CBUUID objects — representing service UUIDs — in the serviceUUIDs parameter. When you do, the peripheral returns only the services of the peripheral that match the provided UUIDs.
>

### PR DESCRIPTION
**Pull request by kscheff**
The fix #68 was on the wrong line, it need to be on the first filter since the ?? will not trigger since the array is unwrapped.

### CODE REVIEW

File: CoreBluetoothMock/Classes/CBMCentralManagerMock.swift [hunk 1]
```diff
@@ -979,7 +990,7 @@ open class CBMPeripheralMock: CBMPeer, CBMPeripheral {
             let initialSize = services!.count
             services = services! + mockServices
                 // Filter all device services that match given list (if set).
-                .filter { serviceUUIDs?.contains($0.uuid) ?? true }
+                .filter { serviceUUIDs?.contains($0.uuid) ?? true || initialSize == 0 }
```
Comment (NickKibish) [inline CoreBluetoothMock/Classes/CBMCentralManagerMock.swift:993]: Could you change the comment to `Filter all device services that match the given list (if set) or include all of them if the initial list is empty` or something like that?

File: CoreBluetoothMock/Classes/CBMPeripheralSpec.swift [hunk 2]
```diff
@@ -76,7 +76,7 @@ public class CBMPeripheralSpec {
     /// The device's advertising data.
     /// Make sure to include `CBAdvertisementDataIsConnectable` if
     /// the device is connectable.
-    public let advertisementData: [String : Any]?
+    public var advertisementData: [String : Any]?
```
Comment (NickKibish) [inline CoreBluetoothMock/Classes/CBMPeripheralSpec.swift:79]: What is the purpose of this change?

File: CoreBluetoothMock/Classes/CBMPeripheralSpecDelegate.swift [hunk 3]
```diff
@@ -225,6 +225,10 @@ public protocol CBMPeripheralSpecDelegate {
                     didReceiveSetNotifyRequest enabled: Bool,
                     for characteristic: CBMCharacteristic)
         -> Result<Void, Error>
+  
+    func peripheral(_ peripheral: CBMPeripheralSpec,
```
Comment (NickKibish) [inline CoreBluetoothMock/Classes/CBMPeripheralSpecDelegate.swift:229]: Could you add a header doc for this method?

**Review by NickKibish — CHANGES_REQUESTED** [review]
Looks good!
Could you just add comments and fix conflicts?
