### PR TITLE
Bugfix: Reconnection

### LINKED ISSUE #113: Reconnection on disconnection when `forceMock == false` does not work due
Hey,

The problem is that when the delegate call 
```swift
centralManager(_:didDisconnectPeripheral:error:)
``` 
is handled, we would like to use it to automatically "reconnect" by calling 
```swift
centralManager.connect(peripheral)
```
since attempts to connect to a peripheral don’t time out.

But it does not work, as after digging into the issue, the underlying `CBPeripheral`s are stored by the `CBMCentralManagerNative` which is removed on [`didDisconnectPeripheral`](https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/blob/b522df5fc0eae2a4ccea1bd8dc732265003a48a3/CoreBluetoothMock/CBMCentralManagerNative.swift#L93) so when `connect` is called it is blocked the [if statement](https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/blob/b522df5fc0eae2a4ccea1bd8dc732265003a48a3/CoreBluetoothMock/CBMCentralManagerNative.swift#L229) as the peripheral is no longer hold in the dictionary.

Potentially a quick fix could be:
```swift
func centralManager(_ central: CBCentralManager,
                    didDisconnectPeripheral peripheral: CBPeripheral,
                    error: Error?) {
    manager.delegate?.centralManager(manager,
                                     didDisconnectPeripheral: getPeripheral(peripheral),
                                     error: error)
    // Check if the error is present otherwise the disconnection was explicit
    if error == nil {
        removePeripheral(peripheral)
    }
}
```
But I guess, the biggest issue is that `CBPeripherals` are strongly hold by `CBMCentralManagerNative` in overall.

### PR DESCRIPTION
**Pull request by philips77**
This PR fixes #113.

As stated in https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/issues/113#issuecomment-2713188259, the solution accepted in #102 introduced a bug preventing from reconnecting to a peripheral using native Central Manager. The peripheral instance was removed from managed peripherals on disconnection and reconnection was failing.

In https://github.com/NordicSemiconductor/IOS-CoreBluetooth-Mock/issues/98#issuecomment-1609597594 a different approach was also proposed, where the mock services were cleared. This PR applies this solution, but making them clear on disconnection (before the callback) to match the actual behavior when using a native API.

This seems to fix the reconnection problem.

Additionally, this PR modifies the sample nRF Blinky app adding a button to reconnect to a peripheral after a disconnection. I18n was fixed for displaying disconnections and some error messages.

### CODE REVIEW

File: Example/nRFBlinky/Models/BlinkyPeripheral.swift [hunk 1]
```diff
@@ -88,7 +88,7 @@ class BlinkyPeripheral: NSObject, CBPeripheralDelegate {
                 self.post(.blinkyDidDisconnect(self, error: nil))
             }
         }
-        onConnected {
+        _ = onConnected {
```
Comment (philips77) [inline Example/nRFBlinky/Models/BlinkyPeripheral.swift:91]: This, and the `onStateChange` observer never gets dispose. But that's not a big deal, as they should live until the app is killed anyway.
